name: Constant Integration

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

# this prevents one PR from simultaneously running multiple runners, which will clog up the queue
# and prevent other PRs from running the CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    env: # update this if needed to match a pull request on the RMG-database
      RMG_DATABASE_BRANCH: main
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      # configures the mamba environment manager
      - name: Setup Mambaforge Python 3.7
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: 3.7
          activate-environment: rmg_env
          use-mamba: true

      # list the environment for debugging purposes
      - name: mamba info
        run: |
          mamba info
          mamba list

      # RMG installation and linking to Julia
      - name: Install and link Julia dependencies
        run: |
          julia -e "using Pkg; Pkg.add(PackageSpec(url=\"https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl\", rev=\"main\"))"
          julia -e "using Pkg; Pkg.add(\"PyCall\"); Pkg.add(\"DifferentialEquations\")"
          python -c "import julia; julia.install()"
          ln -sfn $(which python-jl) $(which python)

      # Attempt to install MOPAC
      - name: Install MOPAC
        env:
          MOPACKEY: ${{ secrets.MOPACKEY }}
        timeout-minutes: 1
        continue-on-error: true # allowed to fail on pull request from a forked repository
        run: |
          set +o pipefail
          yes 'Yes' | ${CONDA_PREFIX}/bin/mopac "$MOPACKEY"

      # Clone the other needed repositories
      - name: Install and compile RMG
        run: |
          cd ..
          git clone -b $RMG_DATABASE_BRANCH https://github.com/ReactionMechanismGenerator/RMG-database.git
          cd RMG-Py
          git clone -b arkanepy3 https://github.com/mjohnson541/Q2DTor.git external/Q2DTor
          make

      # non-regression testing
      - name: Unit tests
        run: make test-unittests
      - name: Functional tests
        if: ${{ success() || failure() }} # Run even if the unit tests failed (but not if they were cancelled)
        run: make test-functional
      - name: Database tests
        if: ${{ success() || failure() }} # Run even if the functional tests failed (but not if they were cancelled)
        run: make test-database

      # Regression Testing
      - name: Regression Tests
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/stable' }} # only push events to branches other than main and stable
        env:
          GH_TOKEN: ${{ secrets.RMG_DEV_TOKEN }}
        run: ./trigger-rmg-tests.sh

      # Install and Call codecov only if ALL the tests were successful
      - name: Code coverage install and run
        run: |
          mamba install -y -c conda-forge codecov
          codecov
